In [1]:
import kagglehub
import string 
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [2]:
# nltk.download("punkt")
# nltk.download("punkt_tab")
# nltk.download("stopwords")

In [3]:

path = kagglehub.dataset_download("mawro73/restaurant-reviews-for-nlp")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\C9IN\.cache\kagglehub\datasets\mawro73\restaurant-reviews-for-nlp\versions\1

In [4]:
import os
os.listdir(path)

['Restaurant_Reviews.tsv']

In [5]:
import  pandas as pd 
file_path = os.path.join(path, "Restaurant_Reviews.tsv")
df = pd.read_csv(file_path, sep="\t")

In [6]:
df.head()

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [7]:
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)
print(df.info())
print(df["Liked"].value_counts())

(1000, 2)
2000
2
Index(['Review', 'Liked'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB
None
Liked
1    500
0    500
Name: count, dtype: int64

In [8]:
df["Review"]=df["Review"].str.lower()

we have two approach to remove the punctuation 1st using the string library and other using re


text = df["Review"][0]

using string

text_without_punctuation = text.translate(str.maketrans('', '', string.punctuation))

using re

text=re.sub(r'[^\w\s]',"",text)

print(text)

In [9]:
df["tokens"]=df["Review"].apply(word_tokenize)

In [10]:

df[["Review", "tokens"]].head()
df["tokens"] = df["tokens"].apply(
    lambda tokens: [word for word in tokens if word.isalnum()]
)

df[["Review", "tokens"]].head()

,Review,tokens
0,wow... loved this place.,"[wow, loved, this, place]"
1,crust is not good.,"[crust, is, not, good]"
2,not tasty and the texture was just nasty.,"[not, tasty, and, the, texture, was, just, nasty]"
3,stopped by during the late may bank holiday of...,"[stopped, by, during, the, late, may, bank, ho..."
4,the selection on the menu was great and so wer...,"[the, selection, on, the, menu, was, great, an..."

In [11]:
stop=set(stopwords.words("English"))
stop = set(stopwords.words("english"))

stop.remove("not")
stop.remove("no")
stop.remove("nor")

In [12]:
df["tokens"]=df["tokens"].apply(lambda token : [word for word in token if word not in stop])