Design and implement a simple linear regression model to predict Sunday newspaper circulation based on weekly newspaper circulation.

Tasks:
Predict Sunday paper circulation for:
200 daily circulation
300 daily circulation
500 daily circulation
Evaluate the model using:
R-square
Adjusted R-square

In [ ]:
import pandas as pd
df_news=pd.read_csv("NewspaperData.csv")

In [ ]:
df_news.head()

In [ ]:
df_news.info()

In [ ]:
df_news.dtypes

In [ ]:
df_news.corr(numeric_only=True)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(df_news["daily"],df_news["sunday"], color="blue" ,alpha=0.5)
plt.title("Scatter Plot of daily vs sunday")
plt.xlabel("Daily Circulation")
plt.ylabel("Sunday Circulation")
plt.show()

1. smf.ols()

OLS means:

Ordinary Least Squares

Ye linear regression model banata hai.

2. "sunday ~ daily"

Formula format:

y∼x

Yahan:

sunday → dependent variable (target)
daily → independent variable (input)

Meaning:

Predict sunday circulation using daily circulation.

3. data=df_news

Batata hai ki data kis dataframe me stored hai.

Yahan:

df_news

dataset ka naam hai.

4. .fit()

Model ko train karta hai.

Matlab:

regression line calculate karega
slope/intercept find karega
best fit equation banayega

In [7]:
import statsmodels.formula.api as smf

model = smf.ols("sunday ~ daily", data=df_news).fit()

In [8]:
model.params

Intercept    13.835630
daily         1.339715
dtype: float64

sunday=13.83+1.33(weekly)

In [9]:
model.pvalues

Intercept    7.017382e-01
daily        6.016802e-19
dtype: float64

predict using model

In [10]:
newdata=pd.Series([200,300,500])

In [14]:
data_pred=pd.DataFrame(newdata,columns=["daily"])

In [12]:
data_pred

   Daily
0    200
1    300
2    500

In [18]:
data_pred["Sunday"]=model.predict(data_pred)
data_pred

   daily      Sunday
0    200  281.778581
1    300  415.750057
2    500  683.693009

In [19]:
model.rsquared

np.float64(0.9180596895873294)

In [20]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 sunday   R-squared:                       0.918
Model:                            OLS   Adj. R-squared:                  0.915
Method:                 Least Squares   F-statistic:                     358.5
Date:                Wed, 06 May 2026   Prob (F-statistic):           6.02e-19
Time:                        20:00:39   Log-Likelihood:                -206.85
No. Observations:                  34   AIC:                             417.7
Df Residuals:                      32   BIC:                             420.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     13.8356     35.804      0.386      0.702     -59.095      86.766
daily          1.3397      0.071     18.935      0.000       1.196       1.484
==============================================================================
Omnibus:                        3.297   Durbin-Watson:                   2.059
Prob(Omnibus):                  0.192   Jarque-Bera (JB):                1.990
Skew:                           0.396   Prob(JB):                        0.370
Kurtosis:                       3.882   Cond. No.                         965.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""